### ISSUE TITLE
Avalonia 11 support.

### ISSUE THREAD

**Issue by qian-o** [arklumpus/Spreadalonia#1]
Hi, Avalonia 11 has been released for some time now. Will this library be updated accordingly?

**Comment by arklumpus** [comment]
Hi! Yes, I will update it eventually, but I really don't have time at the moment, unfortunately 😅

**Comment by arklumpus** [comment]
Version 1.1.0 now supports Avalonia 11, thanks to @piervide for doing the hard part!
